name: Example demonstrating chaining of jobs in a workflow. # as workflows runs in parallel in git actions.

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo job: ${{github.job}}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: "echo job2: ${{github.job}}"

  job3:
    runs-on: ubuntu-latest
    needs: job1      
    steps:
      - run: "echo job3: ${{github.job}}"

  job4:
    runs-on: ubuntu-latest
    needs: [job2,job3]
    steps:
      - run: "echo job4: ${{github.job}}"
      
