name: Testing expressions in workflows and workflow functions.

on: 
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  ifop:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Testing if the workflow is pushed to the main branch or not.
    
    steps:
      - run: |
          echo  "Deploying to branch : ${{github.ref}}"
      - name: Testing the conditional workflow functions.
        if: ${{ 1!=2 }}
        run: |
          echo "Conditional checked and condition success occured"
      - name: Checking if the previous succeeded or not
        if: ${{ success() }} # this func will check the state of jobs executed till now , whether success/failure
        run: echo "Till now all steps are successfully executed"
        
      - name: "Checking for failure"
        if: ${{ failure() }}
        run: echo "Failure met in the execution flow of steps.
        
      - name: Testing the conditional workflow functions.
        if: ${{ 1==2 }}
        run: |
          echo "Conditional checked and failure occured"

      - name: "Checking for failure"
        if: ${{ failure() }}
        run: echo "Failure met in the execution flow of steps."
        
      - name: Testing the conditional workflow functions.
        if: ${{ 1==2 }}
        run: |
          echo "Conditional checked and failure occured"

  add-a-secret:
    runs-on: ubuntu-latest
    name: Adding a secret within the workflow
    steps:
      - id: sets-a-secret # used to access like js in the file later on
        name: Generates masked random secret.
        run: | 
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: "Prints the secret in the previous step"
        run: |
          echo "The secret number is : ${{ steps.sets-a-secret.outputs.secret-number }}"
    
      
      
