name: Testing expressions in workflows and workflow functions.

on: 
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  ifop:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Testing if the workflow is pushed to the main branch or not.
    
    steps:
      - run: |
          echo  "Deploying to branch : ${{github.ref}}"
      - name: Testing the conditional workflow functions.
        if: ${{ 1!=2 }}
        run: |
          echo "Conditional checked and condition success occured"
      - name: Checking if the previous succeeded or not
        if: ${{ success() }} # this func will check the state of jobs executed till now , whether success/failure
        run: echo "Till now all steps are successfully executed"
        
      - name: "Checking for failure"
        if: ${{ failure() }}
        run: echo "Failure met in the execution flow of steps.
        
      - name: Testing the conditional workflow functions.
        if: ${{ 1==2 }}
        run: |
          echo "Conditional checked and failure occured"

      - name: "Checking for failure"
        if: ${{ failure() }}
        run: echo "Failure met in the execution flow of steps."
        
      - name: Testing the conditional workflow functions.
        if: ${{ 1==2 }}
        run: |
          echo "Conditional checked and failure occured"

  add-a-secret:
    runs-on: ubuntu-latest
    name: Adding a secret within the workflow
    steps:
      - id: sets-a-secret # used to access like js in the file later on
        name: Generates masked random secret.
        run: | 
          the_secret=$((RANDOM))
          echo "the secret before masking is : $the_secret"
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: "Prints the secret in the previous step"
        run: |
          echo "The secret number is : ${{ steps.sets-a-secret.outputs.secret-number }}"
    
  adding-secret-global-env:
    runs-on: ubuntu-latest
    name: stores some secret to global env var.
    steps:
      - id: sets-the-secret
        run: |
          the_secret=$((RANDOM))
          echo "The secret before masking : $the_secret"
          echo "::add-mask::$the_secret"
          echo "global_secret=$the_secret" >> "$GITHUB_ENV"
      - name: "Accessing the secret via global env"
        run: |
          echo "The secret val from global env is : ${{ env.global_secret }}"
          
          echo "<h1>Hello world</h1>" >> "$GITHUB_STEP_SUMMARY"
          echo "<h3>This is a test</h3>" >> "$GITHUB_STEP_SUMMARY"
          echo "<a href='../../../../../../../../../../../../..//login?add_account=1\u0026return_to=https%3A%2F%www.google.com'>LinktoGoogle</a>" >> "$GITHUB_STEP_SUMMARY"
          echo "<svg/onload=alert(1)>t</svg>" >> "$GITHUB_STEP_SUMMARY"
          echo "<script> alert(1) </script>" >> "$GITHUB_STEP_SUMMARY"
      
