name: Testing expressions in workflows and workflow functions.

on: 
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  ifop:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Testing if the workflow is pushed to the main branch or not.
    
    steps:
      - run: |
          echo  "Deploying to branch : ${{github.ref}}"
      - name: Testing the conditional workflow functions.
        if: ${{ 1!=2 }}
        if: ${{ success() }}
        run: |
          echo "Conditional checked and condition success occured"
      - name: Testing the conditional workflow functions.
        if: ${{ 1==2 }}
        if: ${{ failure() }}
        run: |
          echo "Conditional checked and failure occured"
      - name: Testing the conditional workflow functions.
        if: ${{ 1==2 }}
        if: ${{ success() }}
        
        run: |
          echo "Conditional checked and failure occured"
