name: First Workflow TEST
on: 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: echo "HI to github workflows"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: |
          echo "This repository {{github.repository}} contains the following files:"
          tree
