name: First Workflow TEST
on: 
  push:
    branches: 
    - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: "Home drive on the machine"
        required: true
      loglevel:
        description: 'Log level'
        required: true
        type: choice
        options:
          - info
          - warn
          - debug
      tag:
        description: "Apply tag after successfull run"
        required: true
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: text
        required: true

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HI to github workflows"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: |
          echo "This repository ${{github.repository}} contains the following files:"
          tree
      - run: |
          echo "Inputs given to this workflows are: "
          echo "Homedrive: ${{inputs.homedrive}}"
          echo "loglevel: ${{inputs.loglevel}}"
          echo "Inputag: ${{inputs.tag}}"
          echo "Env: ${{inputs.environment}}"
      - name: Workflow Inputs
      if: ${{github.event_name == 'workflow_dispatch'}}
          
