name: Using toolkit to parse markdown

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Write summary for action
        uses: actions/github-script@v7.0.1
        with:
          script:
            await core.summary
            .addHeading("test res")
            .addLink("testlink" , "https://evil.com"
            .write()
  
